---
kind: pipeline
type: ssh
name: default

server:
  host: 10.1.3.112
  user: root
  password:
    from_secret: testpassword

steps:
  - name: greeting
    commands:
      - echo hello world
      - wget https://github.com/prometheus/prometheus/releases/download/v2.37.1/prometheus-2.37.1.darwin-amd64.tar.gz
      - echo $test1 > /root/qinjunhang
      



...
