---
kind: pipeline
type: ssh
name: default

server:
  host: 10.1.3.116
  user: root
  password:
    from_secret: testpassword

steps:
  - name: greeting
    commands:
      - echo hello world
      - echo $test1 > /root/qinjunhang



...